apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
spec:
  selector:
    matchLabels:
      run: service4
  template:
    metadata:
      labels:
        run: service4
    spec:
      containers:
      - name: service4
        image: isaaclister/core-project4:latest
        ports:
        - containerPort: 5003
