apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  selector:
    matchLabels:
      run: service2
  template:
    metadata:
      labels:
        run: service2
    spec:
      containers:
      - name: service2
        image: isaaclister/core-project2:latest
        ports:
        - containerPort: 5001
