apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  selector:
    matchLabels:
      run: service3
  template:
    metadata:
      labels:
        run: service3
    spec:
      containers:
      - name: service3
        image: isaaclister/core-project3:latest
        ports:
        - containerPort: 5002
